# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
